### ISSUE TITLE
Fix arrow size in Our Team website links

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#20]
it should be smaller and centered in the circle like the other links. let me know if you need a new graphic from me for this to be possible.

<img width="443" alt="screen shot 2018-09-06 at 10 22 44 am" src="https://user-images.githubusercontent.com/42974047/45163657-df1e2f00-b1be-11e8-9f1f-2949ce9621d5.png">

**Comment by ianbusko** [comment]
@peterhershey How does this look? 
<img width="226" alt="screen shot 2018-09-06 at 1 08 46 pm" src="https://user-images.githubusercontent.com/16769229/45173395-15b37400-b1d6-11e8-8e55-2189c89ba6de.png">

**Comment by peterhershey** [comment]
perfect size. A little off-center? but that may just be an illusion?

**Comment by ianbusko** [comment]
@peterhershey It looks off center because of the angle of the arrow. I
could try adding a few pixels to the left.

**Comment by peterhershey** [comment]
if possible, that would be ideal.
