### ISSUE TITLE
fix sharing links

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#21]
**a few things...**

1. Could the sharing text be "Telling the stories of Karen musicians on the Thai-Burma border - http://www.thenotedproject.org"

2. FB and TW screenshots attached. something's rotten in the state of denmark...
<img width="705" alt="screen shot 2018-09-06 at 10 28 58 am" src="https://user-images.githubusercontent.com/42974047/45164252-1a6d2d80-b1c0-11e8-8d47-5edd52f71dc5.png">
<img width="552" alt="screen shot 2018-09-06 at 10 30 55 am" src="https://user-images.githubusercontent.com/42974047/45164254-1a6d2d80-b1c0-11e8-8a50-aa0f389a0756.png">

3. The email link works, but it also opens up this blank tab to 
[mailto:?subject=The%20Noted%20Project&body=mailto:?subject=The%2520Noted%2520Project&body=http://www.thenotedproject.org], which is kind of weird. is that normal? if so, disregard.

**Comment by peterhershey** [comment]
nav links. I forgot to check the ones in the story slide

**Comment by ianbusko** [comment]
@peterhershey I updated the Site MetaData content in Contentful. You will be able to update twitter share content from there.

**Comment by peterhershey** [comment]
thank you! looks great!
