### ISSUE TITLE
add body copy text to contact us page

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#22]
just a body copy field, same size and style as on the "about us" page, so that we can add a brief paragraph with a link or two

**Comment by ianbusko** [comment]
@peterhershey please mock up a page that shows where you want the body copy to live in the design.

**Comment by peterhershey** [comment]
Here's a rough mockup for body copy placement.

<img width="1303" alt="contactus" src="https://user-images.githubusercontent.com/42974047/45591290-5b7de400-b91c-11e8-9eea-c811fd9246aa.png">

**Comment by ianbusko** [comment]
@peterhershey This will be ready for the next round of revisions.

**Comment by ianbusko** [comment]
@peterhershey the changes are published for review. You have the ability to update your content in Contentful.
