### ISSUE TITLE
change subject line of contact page email

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#23]
from "TNP contact" to "Correspondence from TheNotedProject.org"

**Comment by ianbusko** [comment]
@peterhershey are you sure that's what you want the subject to be? It's not really correspondance _from_ the noted project.

**Comment by peterhershey** [comment]
Correspondence via TheNotedProject.org (?)

**Comment by ianbusko** [comment]
@peterhershey I added this as a configurable value in contentful. Feel free to change it whenever you want.
