### ISSUE TITLE
mobile - homepage background image blurry

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#28]
not sure where that one came from, but I'll get you a new good one. if it's easier, you could also have the position of the background image be fixed... right now it's scrolling but kind of glitchy

**Comment by ianbusko** [comment]
Good call. I just threw a placeholder in there and forgot about it.

**Comment by ianbusko** [comment]
1. It supports up to 5 stories. It'll fail validation if you try to add
more.
2. You should host the intro video on Vimeo. If you want to use the one we
already used, copy the embed url from the iframe on the splash page.

**Comment by peterhershey** [comment]
1. Perfect! that's what I like to hear.
2. So even though it's hosted on Vimeo, you can pull it into the site without any play buttons, overlay graphics, or anything? Just the video? Does it have to be public?

**Comment by ianbusko** [comment]
Good news! The fix is included in the next publish. Bad news! Your image makes the links blend in. Good news! You can update the image in contentful.

**Comment by ianbusko** [comment]
@peterhershey let's talk about a solution for the video background.

**Comment by ianbusko** [comment]
@peterhershey this is ready for review.
