### ISSUE TITLE
Video slides don't play

### ISSUE THREAD

**Issue by ianbusko** [ianbusko/the-noted-project#3]

**Comment by ianbusko** [comment]
@peterhershey you need to update contentful to include the embed link instead of the view link for your videos. (i.e. [https://player.vimeo.com/video/288044655](https://player.vimeo.com/video/288044655) instead of [https://vimeo.com/288044655](https://vimeo.com/288044655))

**Comment by peterhershey** [comment]
updated them to be the player.vimeo links. strictly speaking that's not the embed link, though...

let me know if that works or if I need to change them

**Comment by ianbusko** [comment]
<img width="563" alt="screen shot 2018-09-06 at 1 40 48 am" src="https://user-images.githubusercontent.com/16769229/45171712-1c8bb800-b1d1-11e8-8857-0db570c0d8ce.png">

**Comment by peterhershey** [comment]
are you saying i didn't do it correctly? or are you just pointing that out?

**Comment by ianbusko** [comment]
Just pointing it out. It is technically the embed url.
