### ISSUE TITLE
NEW nav items and order

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#30]
1. Home
2. Our Team
3. Contact
4. Thanks

**Comment by ianbusko** [comment]
@peterhershey is this only on the mobile menu?

**Comment by ianbusko** [comment]
Are we removing the blog?

**Comment by peterhershey** [comment]
Yes. I might add it into the text on the contact page. Or maybe not. But either way removing it from main nav

**Comment by peterhershey** [comment]
Why is this assigned to me?

**Comment by ianbusko** [comment]
I tagged you for your approval next time I publish.

**Comment by peterhershey** [comment]
Gotcha. Thank you!

**Comment by peterhershey** [comment]
Not approved yet. The order should be:

**Comment by ianbusko** [comment]
@peterhershey this is ready for review in the next release.

**Comment by ianbusko** [comment]
@peterhershey this is ready for review.
