### ISSUE TITLE
Fix links on final slide of story

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#31]
1. Facebook link works, but sharing image doesn't show
2. When the twitter link pops up a new tweet, the text field is empty
3. Email link works :)
4. Next Story link just takes you to the same story you are already on

<img width="683" alt="screen shot 2018-09-06 at 11 40 15 am" src="https://user-images.githubusercontent.com/42974047/45168609-b18ab300-b1c9-11e8-812c-dc5b35fe3e4f.png">

**Comment by ianbusko** [comment]
What's your preference on the next story and previous story? I could just
set it to link based on the order that they come from Contentful or I could
add a field in Contentful to specify the next/previous story to ensure
consistency.

**Comment by ianbusko** [comment]
@peterhershey I updated the Story Contentful model to add a field for "Previous Story" and "Next Story". Could you please update your stories and then post an update here?

**Comment by peterhershey** [comment]
updated. that was easy, thank you. we good to go on the sharing links?
