### ISSUE TITLE
mobile - story styling

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#46]
Just a few things with the top part of the stories.

1. There shouldn't be a margin between the first photo and the top of the page.
2. The title of the story (h1 I assume) is way too large. It should be the same size as on the previous test site.
3. The margins for the video section should be more like this:
![mobile-videosection](https://user-images.githubusercontent.com/42974047/45591770-48bddc00-b929-11e8-851e-5432185171d1.jpg)
I believe that would be an improvement not a bug.

**Comment by ianbusko** [comment]
@peterhershey the changes in this are included in the next publish.

**Comment by ianbusko** [comment]
@peterhershey the changes are ready for review.
