### ISSUE TITLE
Splash background is sized incorrectly on most monitors

### ISSUE THREAD

**Issue by ianbusko** [ianbusko/the-noted-project#5]

**Comment by peterhershey** [comment]
I'm assuming this means the video background? it looks like it **fits** to the screen size for me, but doesn't **fill** it.

**Comment by ianbusko** [comment]
Right. Ideally the oframe should resize itself based on the aspect ratio of
the screen.

**Comment by ianbusko** [comment]
@peterhershey this is also fixed in the next release.

**Comment by peterhershey** [comment]
I'll want to give it a look on a smaller laptop though, if you haven't already

**Comment by ianbusko** [comment]
@peterhershey I'll also use the chrome dev tools to try a couple size.
