### ISSUE TITLE
scrolling issues

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#77]
I've heard this from a few people, and then noticed it myself on a few screens.

sometimes when you load a page (I've noticed it on stories, but more often on the thanks/about pages), it just doesn't scroll. scrolling is locked until you refresh page.

**Comment by ianbusko** [comment]
Steps to replicate:
1. Load story
2. Navigate to another page using the nav bar
3. see bug

**Comment by ianbusko** [comment]
@peterhershey I published to a test site. Please review.

**Comment by ianbusko** [comment]
Issue is fixed. Closing issue.
